import { eq, and, isNull, desc } from "drizzle-orm";
import { scrypt, timingSafeEqual } from "crypto";
import { promisify } from "util";
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { db, dbRemote, localSqlite, multiWrite } from "./db.js";
import { cashRegisters, sales, saleItems, payments, transactions, users, products, batches, menuItems, services } from "../shared/schema.js";

const scryptAsync = promisify(scrypt);
const cashRegisterMovements = sqliteTable("cash_register_movements", {
  id: integer("id").primaryKey({ autoIncrement: true }), cashRegisterId: integer("cash_register_id").notNull(), userId: integer("user_id").notNull(), type: text("type").notNull(), amount: integer("amount").notNull(), reason: text("reason"), createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
const cashControlSettings = sqliteTable("cash_control_settings", {
  id: integer("id").primaryKey({ autoIncrement: true }), enterpriseId: integer("enterprise_id").notNull(), toleranceCents: integer("tolerance_cents").notNull().default(0), updatedBy: integer("updated_by").notNull(), updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
const cashRegisterReviews = sqliteTable("cash_register_reviews", {
  id: integer("id").primaryKey({ autoIncrement: true }), registerId: integer("register_id").notNull().unique(), reviewerId: integer("reviewer_id").notNull(), closingAmount: integer("closing_amount").notNull(), difference: integer("difference").notNull(), toleranceCents: integer("tolerance_cents").notNull(), classification: text("classification").notNull(), observation: text("observation"), reviewedAt: integer("reviewed_at", { mode: "timestamp" }).notNull(),
});
const financialTransactionLinks = sqliteTable("financial_transaction_links", {
  id: integer("id").primaryKey({ autoIncrement: true }), transactionId: integer("transaction_id").notNull().unique(), sourceType: text("source_type").notNull(), sourceId: integer("source_id"), cashRegisterId: integer("cash_register_id"), saleId: integer("sale_id"), sessionId: integer("session_id"),
});
const cashNoticeAcks = sqliteTable("cash_notice_acks", {
  id: integer("id").primaryKey({ autoIncrement: true }), registerId: integer("register_id").notNull(), userId: integer("user_id").notNull(), acknowledgedAt: integer("acknowledged_at", { mode: "timestamp" }).notNull(),
});
const CREATE = [
  `CREATE TABLE IF NOT EXISTS cash_control_settings (id INTEGER PRIMARY KEY AUTOINCREMENT, enterprise_id INTEGER NOT NULL UNIQUE, tolerance_cents INTEGER NOT NULL DEFAULT 0, updated_by INTEGER NOT NULL, updated_at INTEGER NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS cash_register_reviews (id INTEGER PRIMARY KEY AUTOINCREMENT, register_id INTEGER NOT NULL UNIQUE, reviewer_id INTEGER NOT NULL, closing_amount INTEGER NOT NULL, difference INTEGER NOT NULL, tolerance_cents INTEGER NOT NULL, classification TEXT NOT NULL, observation TEXT, reviewed_at INTEGER NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS financial_transaction_links (id INTEGER PRIMARY KEY AUTOINCREMENT, transaction_id INTEGER NOT NULL UNIQUE, source_type TEXT NOT NULL, source_id INTEGER, cash_register_id INTEGER, sale_id INTEGER, session_id INTEGER)`,
  `CREATE TABLE IF NOT EXISTS cash_notice_acks (id INTEGER PRIMARY KEY AUTOINCREMENT, register_id INTEGER NOT NULL, user_id INTEGER NOT NULL, acknowledged_at INTEGER NOT NULL)`,
];
async function ensure() { for (const s of CREATE) { try { localSqlite.prepare(s).run(); } catch {} } if (dbRemote) for (const s of CREATE) { try { const c=(dbRemote as any).$client ?? (dbRemote as any).client; if(c?.execute) await c.execute(s); } catch {} } }
async function comparePassword(stored:string,supplied:string){ const [hash,salt]=stored.split("."); if(!hash||!salt)return false; const got=(await scryptAsync(supplied,salt,64)) as Buffer; const exp=Buffer.from(hash,"hex"); return exp.length===got.length&&timingSafeEqual(exp,got); }
function cents(v:unknown,zero=true){const n=Number(v);if(!Number.isFinite(n)||(zero?n<0:n<=0))return null;return Math.round(n*100);}
function money(c:number){return `R$ ${(c/100).toFixed(2).replace(".",",")}`;}
function classify(d:number,t:number){if(d===0)return "CAIXA CONFERIDO";if(Math.abs(d)<=t)return "DENTRO DA TOLERÂNCIA";return d>0?"SOBRA DE CAIXA":"FALTA DE CAIXA";}
async function tolerance(database:any,enterpriseId:number){const [r]=await database.select().from(cashControlSettings).where(eq(cashControlSettings.enterpriseId,enterpriseId)).limit(1);return Number(r?.toleranceCents||0);}
async function calc(database:any,id:number){
  const [register]=await database.select().from(cashRegisters).where(eq(cashRegisters.id,id)).limit(1); if(!register)throw new Error("Caixa não encontrado");
  const rows=await database.select().from(sales).where(eq(sales.cashRegisterId,id)); const completed=rows.filter((s:any)=>s.status==="completed");
  let cashSales=0,cardSales=0,pixSales=0,otherSales=0; const detailedSales:any[]=[];
  for(const sale of completed){ const ps=await database.select().from(payments).where(eq(payments.saleId,sale.id)); for(const p of ps){const a=Number(p.amount||0);if(p.method==="cash")cashSales+=a;else if(p.method==="card")cardSales+=a;else if(p.method==="pix")pixSales+=a;else otherSales+=a;} const items=await database.select().from(saleItems).where(eq(saleItems.saleId,sale.id)); detailedSales.push({sale,payments:ps,items}); }
  const movements=await database.select().from(cashRegisterMovements).where(eq(cashRegisterMovements.cashRegisterId,id)).orderBy(desc(cashRegisterMovements.createdAt));
  const sum=(type:string)=>movements.filter((m:any)=>m.type===type).reduce((s:number,m:any)=>s+Number(m.amount||0),0);
  const replenishments=sum("replenishment"),withdrawals=sum("withdrawal"),adjustments=sum("adjustment");
  const expectedAmount=Number(register.openingAmount||0)+cashSales+replenishments-withdrawals+adjustments;
  return {register,openingAmount:Number(register.openingAmount||0),cashSales,cardSales,pixSales,otherSales,replenishments,withdrawals,adjustments,expectedAmount,movements,detailedSales};
}
async function enrichSale(database:any,sale:any){
  const items=await database.select().from(saleItems).where(eq(saleItems.saleId,sale.id)); const ps=await database.select().from(payments).where(eq(payments.saleId,sale.id));
  const [operator]=sale.userId?await database.select().from(users).where(eq(users.id,sale.userId)).limit(1):[]; const [register]=sale.cashRegisterId?await database.select().from(cashRegisters).where(eq(cashRegisters.id,sale.cashRegisterId)).limit(1):[];
  const enriched:any[]=[];
  for(const item of items){let source:any=null;if(item.itemType==="product"){const bid=item.itemId>=500000?item.itemId-500000:null;if(bid!==null){const [b]=await database.select().from(batches).where(eq(batches.id,bid)).limit(1);source=b?{type:"batch",...b}:null;}if(!source){const [p]=await database.select().from(products).where(eq(products.id,item.itemId)).limit(1);source=p?{type:"product",...p}:null;}}else if(item.itemType==="service"){const [s]=await database.select().from(services).where(eq(services.id,item.itemId)).limit(1);source=s?{type:"service",...s}:null;}else{const [m]=await database.select().from(menuItems).where(eq(menuItems.id,item.itemId)).limit(1);source=m?{type:"menu_item",...m}:null;}enriched.push({...item,source});}
  return {sale,operator:operator?{id:operator.id,username:operator.username,role:operator.role}:null,register:register||null,items:enriched,payments:ps,impactOnCashCents:ps.filter((p:any)=>p.method==="cash").reduce((s:number,p:any)=>s+Number(p.amount||0),0)};
}

export async function registerCashAudit(app:any,isAuthenticated:any){
  await ensure();
  const admin=(req:any,res:any,next:any)=>{if(!req.isAuthenticated())return res.status(401).json({message:"Unauthorized"});const u=req.user as any;if(!["admin","owner"].includes(u.role))return res.status(403).json({message:"Acesso exclusivo administrativo."});next();};
  app.get("/api/cash-audit/config",admin,async(req:any,res:any)=>res.json({toleranceCents:await tolerance(db,Number((req.user as any).enterpriseId||0))}));
  app.post("/api/cash-audit/config",admin,async(req:any,res:any)=>{const u=req.user as any,pw=String(req.body?.password||""),tc=cents(req.body?.tolerance,true);if(tc===null||!pw)return res.status(400).json({message:"Tolerância e senha administrativa são obrigatórias."});const [du]=await db.select().from(users).where(eq(users.id,u.id)).limit(1);if(!du||!(await comparePassword(du.password,pw)))return res.status(401).json({message:"Senha administrativa incorreta."});const enterpriseId=Number(u.enterpriseId||0);if(!enterpriseId)return res.status(400).json({message:"Estabelecimento não identificado."});await multiWrite(async(database:any)=>{const [ex]=await database.select().from(cashControlSettings).where(eq(cashControlSettings.enterpriseId,enterpriseId)).limit(1);const now=new Date();if(ex)await database.update(cashControlSettings).set({toleranceCents:tc,updatedBy:u.id,updatedAt:now}).where(eq(cashControlSettings.id,ex.id));else await database.insert(cashControlSettings).values({enterpriseId,toleranceCents:tc,updatedBy:u.id,updatedAt:now});});res.json({toleranceCents:tc});});
  app.get("/api/cash-audit/review/:id",admin,async(req:any,res:any)=>{try{const id=Number(req.params.id),data=await calc(db,id);const [review]=await db.select().from(cashRegisterReviews).where(eq(cashRegisterReviews.registerId,id)).limit(1);const [operator]=await db.select().from(users).where(eq(users.id,data.register.userId)).limit(1);const tol=review?Number(review.toleranceCents):await tolerance(db,Number((req.user as any).enterpriseId||0));res.json({...data,operator:operator?{id:operator.id,username:operator.username,role:operator.role}:null,toleranceCents:tol,review:review||null});}catch(e:any){res.status(404).json({message:e.message});}});
  const finalize=async(req:any,res:any)=>{const u=req.user as any,pw=String(req.body?.password||""),id=Number(req.body?.registerId),closing=cents(req.body?.closingAmount,true),observation=String(req.body?.observation||"").trim()||null;if(!id||closing===null||!pw)return res.status(400).json({message:"Dados incompletos para fechamento."});const [du]=await db.select().from(users).where(eq(users.id,u.id)).limit(1);if(!du||!(await comparePassword(du.password,pw)))return res.status(401).json({message:"Senha administrativa incorreta."});const out=await multiWrite(async(database:any)=>database.transaction(async(tx:any)=>{const [r]=await tx.select().from(cashRegisters).where(eq(cashRegisters.id,id)).limit(1);if(!r)throw new Error("Caixa não encontrado.");if(!["open","closed_pending_review"].includes(r.status))throw new Error("Este Caixa já está fechado.");const [old]=await tx.select().from(cashRegisterReviews).where(eq(cashRegisterReviews.registerId,id)).limit(1);if(old)throw new Error("Este fechamento já foi revisado.");const s=await calc(tx,id),tol=await tolerance(tx,Number(u.enterpriseId||0)),difference=closing-s.expectedAmount,classification=classify(difference,tol),now=new Date();await tx.update(cashRegisters).set({closingAmount:closing,difference,closedAt:r.closedAt||now,status:"closed"}).where(eq(cashRegisters.id,id));await tx.insert(cashRegisterReviews).values({registerId:id,reviewerId:u.id,closingAmount:closing,difference,toleranceCents:tol,classification,observation,reviewedAt:now});await tx.insert(cashRegisterMovements).values({cashRegisterId:id,userId:u.id,type:"closing",amount:closing,reason:`Revisão administrativa — ${classification} — diferença ${money(difference)}`,createdAt:now});if(difference!==0){const [t]=await tx.insert(transactions).values({businessType:"padaria",type:difference>0?"income":"expense",category:"caixa_fechamento",description:`${classification} — Caixa #${id} — esperado ${money(s.expectedAmount)} — físico ${money(closing)} — diferença ${money(difference)}`,amount:Math.abs(difference),createdAt:now} as any).returning();await tx.insert(financialTransactionLinks).values({transactionId:t.id,sourceType:"cash_register_review",sourceId:id,cashRegisterId:id,sessionId:id});}return {register:{...r,closingAmount:closing,difference,closedAt:r.closedAt||now,status:"closed"},summary:{...s,closingAmount:closing,difference},toleranceCents:tol,classification,observation};}));res.json(out);};
  app.post("/api/cash-audit/close",admin,finalize);app.post("/api/cash-audit/review",admin,finalize);
  app.get("/api/cash-audit/previous-notice",isAuthenticated,async(req:any,res:any)=>{const rows=await db.select().from(cashRegisters).where(eq(cashRegisters.status,"closed")).orderBy(desc(cashRegisters.closedAt));for(const r of rows){const [rv]=await db.select().from(cashRegisterReviews).where(eq(cashRegisterReviews.registerId,r.id)).limit(1);if(rv&&(rv.observation||Number(rv.difference)!==0)){const [ack]=await db.select().from(cashNoticeAcks).where(and(eq(cashNoticeAcks.registerId,r.id),eq(cashNoticeAcks.userId,(req.user as any).id))).limit(1);if(!ack)return res.json({register:r,review:rv,acknowledged:false});}}res.json({register:null,review:null,acknowledged:true});});
  app.post("/api/cash-audit/previous-notice/:id/ack",isAuthenticated,async(req:any,res:any)=>{const id=Number(req.params.id),u=req.user as any;await multiWrite(async(database:any)=>database.insert(cashNoticeAcks).values({registerId:id,userId:u.id,acknowledgedAt:new Date()}));res.json({ok:true});});
  app.get("/api/finance/details/sale/:id",admin,async(req:any,res:any)=>{const id=Number(req.params.id),[sale]=await db.select().from(sales).where(eq(sales.id,id)).limit(1);if(!sale)return res.status(404).json({message:"Venda não encontrada."});res.json(await enrichSale(db,sale));});
  app.get("/api/finance/details/transaction/:id",admin,async(req:any,res:any)=>{const id=Number(req.params.id),[t]=await db.select().from(transactions).where(eq(transactions.id,id)).limit(1);if(!t)return res.status(404).json({message:"Lançamento não encontrado."});const [link]=await db.select().from(financialTransactionLinks).where(eq(financialTransactionLinks.transactionId,id)).limit(1);let source:any=null;const m=String(t.description||"").match(/(?:Venda|ESTORNO: Venda PDV)\s*#(\d+)/i);if(m){const [sale]=await db.select().from(sales).where(eq(sales.id,Number(m[1]))).limit(1);if(sale)source=await enrichSale(db,sale);}if(!source&&link?.cashRegisterId){const [register]=await db.select().from(cashRegisters).where(eq(cashRegisters.id,link.cashRegisterId)).limit(1);if(register)source={register};}res.json({transaction:t,link:link||null,source});});
  app.get("/api/cash-audit/notices",admin,async(_req:any,res:any)=>res.json(await db.select().from(cashRegisterReviews).orderBy(desc(cashRegisterReviews.reviewedAt))));
}
