import { useCallback, useEffect, useState } from "react";
import { apiRequest } from "@/lib/queryClient";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useToast } from "@/hooks/use-toast";
import { AlertTriangle, LockKeyhole, Settings2, ShieldCheck, UnlockKeyhole } from "lucide-react";

type CashStatus = { register: { status: string } | null };
type Notice = { register: any | null; review: any | null; acknowledged: boolean };
const money = (c: number) => `R$ ${(Number(c || 0) / 100).toFixed(2).replace(".", ",")}`;
const fmt = (d: any) => { const x = new Date(d); return Number.isNaN(x.getTime()) ? "Data indisponível" : x.toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" }); };

export default function CashRegisterOpeningFallback() {
  const queryClient = useQueryClient(); const { toast } = useToast();
  const [visible, setVisible] = useState(false), [menuOpen, setMenuOpen] = useState(false), [dialogOpen, setDialogOpen] = useState(false), [noticeOpen, setNoticeOpen] = useState(false);
  const [amount, setAmount] = useState(""), [password, setPassword] = useState(""); const [position, setPosition] = useState({ left: 0, top: 0 });
  const { data: status } = useQuery<CashStatus>({ queryKey: ["/api/cash-control/status"], queryFn: async () => { const r = await fetch("/api/cash-control/status"); if (!r.ok) throw new Error("Não foi possível consultar o Caixa."); return r.json(); }, refetchInterval: 15000, staleTime: 5000 });
  const { data: notice } = useQuery<Notice>({ queryKey: ["/api/cash-audit/previous-notice"], queryFn: async () => { const r = await fetch("/api/cash-audit/previous-notice"); if (!r.ok) throw new Error("Não foi possível consultar ocorrências do fechamento anterior."); return r.json(); }, refetchInterval: 15000, staleTime: 5000 });
  const registerOpen = !!status?.register && status.register.status === "open";
  const sync = useCallback(() => {
    if (document.querySelector("h3") && Array.from(document.querySelectorAll("h3")).some(h => h.textContent?.toLowerCase().includes("itens no carrinho"))) { setVisible(false); return; }
    const legacy = Array.from(document.querySelectorAll("button")).find(n => n.textContent?.toLowerCase().includes("iniciar turno")) as HTMLButtonElement | undefined;
    if (!legacy) { setVisible(false); return; }
    const card = legacy.closest("div[class*='rounded-2xl']") || legacy.parentElement?.parentElement; if (!card) { setVisible(false); return; }
    legacy.dataset.auraLegacyHidden = "true"; legacy.style.display = "none"; const r = (card as HTMLElement).getBoundingClientRect(); setPosition({ left: Math.max(12, r.right - 190), top: Math.max(76, r.top + 20) }); setVisible(!registerOpen);
  }, [registerOpen]);
  useEffect(() => { const run = () => sync(); const t = window.setTimeout(run, 100); const o = new MutationObserver(run); o.observe(document.body, { childList: true, subtree: true }); window.addEventListener("resize", run); window.addEventListener("scroll", run, true); return () => { clearTimeout(t); o.disconnect(); window.removeEventListener("resize", run); window.removeEventListener("scroll", run, true); }; }, [sync]);
  useEffect(() => { if (notice?.register && !notice.acknowledged) setNoticeOpen(true); }, [notice]);
  const openCash = async () => { const n = Number(amount.replace(",", ".")); if (!Number.isFinite(n) || n < 0) { toast({ title: "Valor inicial inválido", variant: "destructive" }); return; } try { const r = await apiRequest("POST", "/api/cash-control/open", { openingAmount: n, password }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.message || "Não foi possível abrir o Caixa."); await queryClient.invalidateQueries({ queryKey: ["/api/cash-control/status"] }); setDialogOpen(false); setMenuOpen(false); setPassword(""); setAmount(""); toast({ title: "Caixa aberto com sucesso" }); if (notice?.register && !notice.acknowledged) setNoticeOpen(true); } catch (e: any) { toast({ title: "Falha na abertura", description: e.message || "Erro inesperado.", variant: "destructive" }); } };
  const acknowledge = async () => { if (!notice?.register) return; try { await apiRequest("POST", `/api/cash-audit/previous-notice/${notice.register.id}/ack`, {}); await queryClient.invalidateQueries({ queryKey: ["/api/cash-audit/previous-notice"] }); setNoticeOpen(false); toast({ title: "Ocorrência registrada como ciência" }); } catch (e: any) { toast({ title: "Não foi possível registrar ciência", description: e.message, variant: "destructive" }); } };
  if (!visible) return null;
  return <>
    <div className="fixed z-[90]" style={{ left: position.left, top: position.top }}><div className="relative">
      {menuOpen && <div className="absolute right-0 top-11 w-[300px] rounded-2xl border border-white/10 bg-zinc-950/98 backdrop-blur-xl shadow-2xl p-2"><div className="px-3 py-2 border-b border-white/5 mb-1"><span className="text-white font-black uppercase italic text-[10px] tracking-widest">Opções do Caixa</span><p className="text-white/30 text-[8px] uppercase tracking-widest mt-1">Caixa fechado</p></div><button className="w-full flex items-center gap-3 rounded-xl px-3 py-3 text-left text-white/90 hover:text-primary hover:bg-white/5" onClick={() => { setDialogOpen(true); setMenuOpen(false); }}><UnlockKeyhole className="w-4 h-4 text-primary"/><span className="text-[9px] font-black uppercase italic tracking-widest">Abertura do Caixa</span></button>{notice?.register && !notice.acknowledged && <button className="w-full flex items-center gap-3 rounded-xl px-3 py-3 mt-1 text-left bg-amber-500/10 border border-amber-500/20" onClick={() => setNoticeOpen(true)}><AlertTriangle className="w-4 h-4 text-amber-400"/><span className="text-[9px] font-black uppercase italic tracking-widest text-amber-300">Ocorrência do fechamento anterior</span></button>}<div className="px-3 pb-2 pt-1 text-[8px] text-white/25 uppercase tracking-widest flex items-center gap-1.5"><LockKeyhole className="w-3 h-3"/> Fechamento indisponível com o Caixa fechado</div></div>}
      <Button type="button" variant="outline" aria-label="Opções do Caixa" onClick={() => setMenuOpen(v => !v)} className="h-9 px-2.5 rounded-xl bg-zinc-950/95 border-white/10 text-white hover:text-primary hover:border-primary/40 shadow-xl backdrop-blur-md gap-1.5"><Settings2 className="w-4 h-4"/><span className="text-[9px] font-black uppercase italic tracking-widest">Opções do Caixa</span></Button>
    </div></div>
    <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent className="bg-zinc-950 border-white/10 text-white sm:max-w-md"><DialogHeader><DialogTitle className="uppercase italic tracking-tighter text-2xl font-black flex items-center gap-2"><UnlockKeyhole className="w-5 h-5 text-primary"/> Abertura do Caixa</DialogTitle><DialogDescription className="text-zinc-400">Operação administrativa. Use a mesma senha utilizada para entrar na plataforma do estabelecimento.</DialogDescription></DialogHeader><div className="space-y-4 py-3"><div><label className="text-white/40 text-[9px] font-black uppercase tracking-widest">Saldo inicial / troco</label><Input value={amount} onChange={e => setAmount(e.target.value)} inputMode="decimal" placeholder="0,00" className="mt-2 h-14 bg-black border-white/10 text-xl text-primary font-black text-center rounded-xl" autoFocus /></div><div><label className="text-white/40 text-[9px] font-black uppercase tracking-widest flex items-center gap-2"><ShieldCheck className="w-3.5 h-3.5 text-primary"/> Senha administrativa</label><Input type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Senha de acesso à plataforma" className="mt-2 h-12 bg-black border-white/10 text-white rounded-xl" onKeyDown={e => e.key === "Enter" && void openCash()} /></div></div><DialogFooter><Button variant="outline" onClick={() => setDialogOpen(false)} className="border-white/10 text-white bg-transparent">Cancelar</Button><Button onClick={() => void openCash()} disabled={!password || !amount} className="bg-primary text-black font-black uppercase italic">Abrir Caixa</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={noticeOpen} onOpenChange={setNoticeOpen}><DialogContent className="bg-zinc-950 border-amber-500/20 text-white sm:max-w-lg"><DialogHeader><DialogTitle className="uppercase italic tracking-tighter text-2xl font-black flex items-center gap-2"><AlertTriangle className="w-5 h-5 text-amber-400"/> Pendência do fechamento anterior</DialogTitle><DialogDescription className="text-zinc-400">Há uma ocorrência registrada no fechamento anterior que requer ciência.</DialogDescription></DialogHeader>{notice?.register && notice?.review && <div className="space-y-4"><div className="rounded-xl border border-white/10 bg-white/5 p-4 grid grid-cols-2 gap-3 text-xs"><span>Caixa <b>#{notice.register.id}</b></span><span>Sessão <b>#{notice.register.id}</b></span><span>Encerrado <b>{fmt(notice.register.closedAt)}</b></span><span>Situação <b>{notice.review.classification || (notice.review.difference === 0 ? "CAIXA CONFERIDO" : notice.review.difference > 0 ? "SOBRA DE CAIXA" : "FALTA DE CAIXA")}</b></span></div><div className="rounded-xl border border-white/10 p-4 space-y-1"><div className="flex justify-between text-[10px] uppercase font-black tracking-widest"><span>Diferença</span><b>{money(notice.review.difference || 0)}</b></div><div className="flex justify-between text-[10px] uppercase font-black tracking-widest"><span>Tolerância</span><b>{money(notice.review.toleranceCents || 0)}</b></div></div><div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-4"><div className="text-[9px] uppercase tracking-widest font-black text-amber-300">Observação administrativa</div><p className="mt-2 text-sm text-white/70">{notice.review.observation || "Nenhuma observação registrada."}</p></div></div>}<DialogFooter><Button onClick={() => void acknowledge()} className="bg-primary text-black font-black uppercase italic">Tomar ciência</Button></DialogFooter></DialogContent></Dialog>
  </>;
}
